.\"
.\" Public domain
.\"
.TH educ_noip 1 "February 2016" "Enhanced DUC"
.SH NAME
Enhanced DUC \- Dynamic DNS update client and daemon
.SH SYNOPSIS
.B educ_noip
[OPTION] ...
.SH DESCRIPTION
.B Enhanced DUC
is a dynamic DNS update client and daemon. Primarily it's written for
use with the DNS services that
.I noip.com
provide. However: the protocol "is in an open format used by other
service providers".
.SH OPTIONS
.TP
.BI "\-c "
Create a config file and exit. (Will prompt for a location.)
.TP
.BI "\-x " path
Load a config file from a custom location.
.TP
.BI "\-B "
Run in the background as a daemon.
.SH FILES
.TP
.I /etc/educ_noip.conf
Global configuration file.
.SH GOOD TO KNOW
.PP
If the program isn't running as a daemon it can be terminated with
CTRL+C.
.PP
If port 443 is specified SSL will be enabled.
.PP
Valid ports are 80, 443 and 8245.
.SH AUTHOR
.B Enhanced DUC
was written by Markus Uhlin <markus.uhlin@bredband.net>.
