#!/bin/sh

TARGETS="
include/*.h
source/*.c
source/*.cpp
source/*.h
source/*.hpp
tests/*.c
tests/*.h
"

if [ $# != 2 ]; then
	echo "error: bogus number of arguments"
	exit 1
fi

if [ -z "$1" ]; then
	echo "error: first argument is of zero length"
	exit 1
fi

for target in $TARGETS; do
	sed -i "s/$1/$2/g" "$target"
done
