#!/bin/sh

SUFFIX=.run
TESTS="
is_numeric
net_ssl_check_hostname
size_product
strToLower
strdup_printf
trim
xstrdup
"

for t in $TESTS; do
	echo "--- ${t}${SUFFIX} ---"

	if [ -x "${t}${SUFFIX}" ]; then
		"./${t}${SUFFIX}"
	fi
done
