#!/bin/sh

SUFFIX=.run
TESTS="
is_numeric
size_product
strToLower
strdup_printf
trim
xstrdup
"

for name in $TESTS; do
    echo "========== ${name}${SUFFIX} =========="

    if test -f "${name}${SUFFIX}"; then
	./"${name}${SUFFIX}"
    fi
done
